title: Connector SDK
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Falafel stuff here
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

# logo: "https://tray.io/favicon-32x32.png"

color_scheme: light

search:
  heading_level: 3

aux_links:
  "Falafel on GitHub":
    - "//github.com/trayio/falafel"
